### PR TITLE
feat: add pyproject-fmt

### PR DESCRIPTION
**Pull request by henryiii**
Adds a toggle and a formatter for `pyproject.toml`.

### CODE REVIEW

**Comment by henryiii** [comment]
(Not quite ready, and also should format the example we give to match)

**Comment by eduardo-rodrigues** [comment]
Hey @henryiii, I just bumped into this WIP PR. Is it that it got forgotten? Just out of curiosity.

**Comment by henryiii** [comment]
It wasn't good enough (pyproject-fmt, not this PR) for us yet. I think it still needs a bit of work; in the next few months hopefully I'll have time to contribute a bit and then it will be useful for us.

**Comment by eduardo-rodrigues** [comment]
Got it. Thanks.

**Pull request closed without merging**
