### PR TITLE
Add QR codes for project and packages

### PR DESCRIPTION
**Pull request by eduardo-rodrigues**

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
I added a page pages/developers/qr_codes.md that so far contains an intro sentence but actually lists no QR codes. One could dynamically produce a table or list similarly to what is done for https://scikit-hep.org/documentation, but I would not know how to do it with Jekyll. Would anyone be able to help?

**Review by HDembinski — APPROVED** [review]

**Comment by henryiii** [comment]
Could you please put this under packages instead? It's not a "developers" page; the Developer guidelines do not discuss the existing packages, but discuss how you develop code for Python. The "packages" pages do list out all the existing projects on various pages like documentation.

**Comment by eduardo-rodrigues** [comment]
> Could you please put this under packages instead? It's not a "developers" page; the Developer guidelines do not discuss the existing packages, but discuss how you develop code for Python. The "packages" pages do list out all the existing projects on various pages like documentation.

Sure. Have no strong feeling. I drafted under the developers directory because QR codes are useful for developers. But fair enough that is is a part of the material related to the packages.

In that respect, should I make a new page as now here or rather add a column to the table under https://scikit-hep.org/documentation? Maybe a separate page is a bit better.

**Comment by henryiii** [comment]
Yes, I think a separate page is fine.

**Comment by eduardo-rodrigues** [comment]
> Yes, I think a separate page is fine.

OK, done. I will see how to list the PNG available unless you can help out with the Jekyll. Thank you.

**Comment by henryiii** [comment]
I can help later this week if needed.

**Comment by eduardo-rodrigues** [comment]
OK @henryiii, I tried a very simple way of displaying the images. I did not check building the site as it is as bit of a pain on Windows (though I should try sometime with WSL!).

**Comment by eduardo-rodrigues** [comment]
@henryiii, are you then able to build the site locally and test that what I wrote displays just fine?

**Comment by eduardo-rodrigues** [comment]
Seems to do the job at least. The pics are downloaded. If OK as a version 0 at least, then approve and we get this in :).

Thanks very much for the quick help!

**Review by henryiii — APPROVED** [review]

**Comment by eduardo-rodrigues** [comment]
Cool, let's 🚀 it!

**Pull request merged**
