### PR TITLE
Feature/improve css startup

### PR DESCRIPTION
**Pull request by KubaO**
Improve startup rendering and get rid of flicker in some browsers. That was caused by using a default stylesheet and only switching it after it was loaded. Instead, we let the browser's renderer do the right thing.

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
Thank you your for contribution.

I'm no expert but this looks reasonable. What do you think @henryiii and/or @matthewfeickert?

@KubaO, do you happen to have a couple of snapshots of the issues you found and the updated version with them fixed?

**Comment by KubaO** [comment]
The problem manifests on first page load (cold caches) in chromium based browsers and is especially jarring in the Edge browser. There’s a bright white flash while the page loads, since the background is selected from the wrong css, and then as soon as the script switches the style sheet, the dark stylesheet has to be loaded and only then can the page be properly rendered. So it slows down initial page display and blinds you at night :)

I’ve been pushed to solve this problem while working on my own personal page that uses this same theme.

I’m not sure what snapshots those would be – page load profile traces show what’s up. Is that what you meant? I could attach some before/after pictures of the traces.

**Comment by eduardo-rodrigues** [comment]
No worries, I understand that it's not obvious to catch the temporary status of the page. Forget about it.

Am approving and will just wait for an extra pair of eyes. Again thank you for the contribution.

**Review by eduardo-rodrigues — APPROVED** [review]

**Comment by henryiii** [comment]
> I’ll try to get this submitted upstream and will then drop another PR that will remove the `head.html` include.

I tried to get the current js version submitted upstream in January (https://github.com/pmarsceill/just-the-docs/pull/560) and was blocked by this very issue (and I think it was also Edge that was the most obvious).

Does this switch if you change the light/dark scheme after loading the page?

**Comment by KubaO** [comment]
Yep, it’s automagical almost :)

**Comment by henryiii** [comment]
Would you like me to update my PR with this version? I'm happy to have you directly contribute if you'd rather. For us, let's merge this and see what it looks like live. :)

**Comment by KubaO** [comment]
Feel free to update your PR. Less work for me :) Thank you!

**Pull request merged**
