### PR TITLE
style: fix recent issues

### LINKED ISSUE #65: Style check
The style seems to be somewhat broken (mentioned in #64 ). Investigate.

### PR DESCRIPTION
**Pull request by henryiii**
After the just-the-docs 0.3.0 update, several style issues have been bothering us, this should fix them. Closes #65 .

This add a search bar, which fixes the misaligned link (reported upstream in https://github.com/pmarsceill/just-the-docs/issues/396). The newly redesigned search is quite nice.

Dropping the custom styling on the navbar, as they no longer work properly. The updated 0.3.0 nav looks pretty good, and I believe the old nesting issues are now fixed.

Add a link to the source repo, addresses #69. I'd like to have a standard "edit this page" button here instead in the near future, opened a GitHub Discussion about it https://github.com/pmarsceill/just-the-docs/discussions/397 .

### CODE REVIEW

**Comment by henryiii** [comment]
With some help from the discussion on just-the-docs, I have a nice, elegant little link at the bottom now that jumps to the source. Other than that, this is just fixes. The new menu is _much_ better on mobile (no more massive scikit-hep logo when opening the menu). @eduardo-rodrigues , if there are any problems, let me know, otherwise we should merge very soon to fix the broken styling.

**Comment by henryiii** [comment]
PS: we were hacking the logo in before, now there's a dedicated feature for it, so I just had to tweak the style a bit.

**Comment by henryiii** [comment]
Extra bonus: you can now click on the logo and that jumps to home, and Scikit-HEP is not repeated right above it. :)

Before:

Screen Shot 2020-07-28 at 11 52 50 PM

After:

Screen Shot 2020-07-28 at 11 56 00 PM

**Comment by eduardo-rodrigues** [comment]
This sounds great, so go ahead and merge.

The only thing I don't see fixed is the colour of links, which is still violet in the snapshot above whereas we had them in a blue as in the logo in the past - much nicer. I did not check (on hols) but it must be a simple update of an hex code :-).

**Comment by henryiii** [comment]
Found it! Part of the same 0.3.0 update. They moved style options out of the main css into loadable theme files. So we just need to move our custom link color to a new file. In fact, [in the docs](https://pmarsceill.github.io/just-the-docs/docs/customization/#define-a-custom-scheme):


> For example, to change the link color from the **purple default to blue**, include the following inside your scheme file:
> 
> ```
> EXAMPLE
> $link-color: $blue-000;
> ```

(emphasis mine) Can't get much closer than that! Will fix and make a new PR.

**Pull request merged**
