### PR TITLE
Add page on funding

### PR DESCRIPTION
**Pull request by eduardo-rodrigues**
Hi @jpivarski, @henryiii, @HDembinski, @marinang, I'm starting a page on funding for Scikit-HEP as I have been made aware that this is very important/requested thing at least in the US. I don't see why we should not acknowledge the funds that directly or indirectly make it possible for us to do this work.

Could you kindly have a look and add text/corrections/suggestions as you see fit?

Many thanks.

### CODE REVIEW

**Comment by HDembinski** [comment]
Good idea. I don't get funding for my work, unfortunately.

**Comment by eduardo-rodrigues** [comment]
Thanks @HDembinski for having a look. You have no grant per se but you could acknowledge (indirect) support from MPK? Seems good to me, and it will also show that the project is widespread ...

**Comment by marinang** [comment]
@eduardo-rodrigues I agree, I don't thing I get funding for my PhD too, apart from EPFL obviously.

**Comment by eduardo-rodrigues** [comment]
@marinang, you could add a sentence thanking EPFL/FNS for effectively funding your time on the project … 

Up to you guys. As said, I see that US funding bodies are *very* picky about these matters, and I thought I would ping you just in case :-).

**Pull request merged**
