### PR TITLE
Add several Gitter links

### PR DESCRIPTION
**Pull request by eduardo-rodrigues**

### CODE REVIEW

**Comment by henryiii** [comment]
How about PyHEP-Histogramming?

**Comment by eduardo-rodrigues** [comment]
I did not try and be comprehensive on the HSF channels, as that's the business of the PyHEP WG and its page https://hepsoftwarefoundation.org/workinggroups/pyhep.html. The 2 ones seems the immediately relevant to mention. You would welcome a list for the HSF as well?

**Comment by henryiii** [comment]
It's just that "PyHEP-Histogramming" is basically the Hist/boost-histogram version of the iminuit/uproot/awkward channels. Since it's "broader" than one package, it went there, but it should be viewed similarly. We link to it directly from Hist/boost-histogram, unlike the other HSF channels.

**Comment by eduardo-rodrigues** [comment]
Updated. How about now?

**Comment by henryiii** [comment]
Looks good. :)

**Pull request merged**
