### PR TITLE
Introduce a News page

### PR DESCRIPTION
**Pull request by eduardo-rodrigues**
Closes https://github.com/scikit-hep/scikit-hep.github.io/issues/42.

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
This is just the start. Of course there are far more news to add, but that's a bit time-consuming. First it is better to agree on the format. Thanks.

**Comment by eduardo-rodrigues** [comment]
OK, I stop here as a v0 of the news page. This is more than enough. I commit myself to updating this in the next week or so following a merge :-).

**Review by HDembinski — APPROVED** [review]
Looks good to me.

**Comment by eduardo-rodrigues** [comment]
Happy as well, @henryiii?

**Comment by henryiii** [comment]
Looks like a deployment error, and not one caused by the PR itself.

**Pull request merged**
