### PR TITLE
News - awkward accepted as an affiliated project of NumFOCUS

### PR DESCRIPTION
**Pull request by eduardo-rodrigues**
* awkward was accepted as an Affiliated Project of NumFOCUS in March 2023.

@jpivarski, @matthewfeickert, can you confirm the date?

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
While at it, do you know of any other piece of news to add for this year?

**Review by jpivarski — APPROVED** [review]
The date of the announcement email was March 16.

**Comment by eduardo-rodrigues** [comment]
Thanks. Updated.

**Comment by matthewfeickert** [comment]
Thanks @eduardo-rodrigues. If you think it is newsworthy enough I can also open up a PR for pyhf being in the [May 2023 NumFOCUS newsletter](https://numfocus.salsalabs.org/numfocus__newsletter_may2023) (not a newsworthy even every time, but as this is the first time I thought maybe)

**Pull request merged**
