### PR TITLE
Add more use citations - Scikit-HEP, pylhe, etc.

### PR DESCRIPTION
**Pull request by eduardo-rodrigues**
FYI @HDembinski, @henryiii and @jpivarski, I found the first citations of `pyhepmc` and `Vector` :-).

### CODE REVIEW

**Comment by HDembinski** [comment]
Cool

**Comment by jpivarski** [comment]
I second that, and want to point out the Vector citation to @Saransh-cpp.

**Comment by Saransh-cpp** [comment]
> want to point out the Vector citation to @Saransh-cpp.

Nice!! Should we also add this somewhere in vector's docs, or would that be redundant?

**Comment by eduardo-rodrigues** [comment]
> > want to point out the Vector citation to @Saransh-cpp.
> 
> Nice!! Should we also add this somewhere in vector's docs, or would that be redundant?

I find it a bit redundant and requires more maintenance but it's up the maintainers in the end, right? I think a few packages in the org have citations listed somewhere, others do not. In any case I try hard to maintain the citations page on the site as I find it nice.

**Pull request merged**
