### PR TITLE
Add hepstats logo

### PR DESCRIPTION
**Pull request by mayou36**
Added the hepstats logo to the website

@marinang can you confirm it's fine?

### CODE REVIEW

**Comment by marinang** [comment]
@mayou36 yeah sure. Thanks for doing that :)

**Comment by mayou36** [comment]
@marinang do you have one? I'll swap it then.
@eduardo-rodrigues we're not able to create branches here, right? This is why I forked. Or did I just not manage to do it?

**Comment by eduardo-rodrigues** [comment]
Oh, could it be because you are member of the org and not owner, as I've just checked? I may have had this issue but am no longer sure: for example for the HSF the guidelines are to always fork.
I can just make you owner if that helps you?

**Comment by mayou36** [comment]
I see, so I can only create branches in `Vector`, I don't have write access anywhere else, but whatever rights are common here. About forking policy, is the same valid for Scikit-HEP or do we work on common branches/free? I didn't find anything in the guidelines for devs

**Comment by eduardo-rodrigues** [comment]
Indeed we have not written any guidelines for branching or forking. Everyone does according to preference, I believe. I tend to branch for my packages by default but do not always fork either for somebody else's package, to be honest. Do as you prefer … I made you owner in the org. You should not be able to do anything - be careful ;-)!

**Comment by eduardo-rodrigues** [comment]
BTW @mayou36, the dev guidelines are by and for all, so you're free to suggest additions to it … Either with a direct PR or first discussing some thoughts on our admins list ...

**Comment by eduardo-rodrigues** [comment]
@marinang do you have such a logo with a transparent background? If you don't, can you make one from the logo you presently have, and add it also in the hepstats repo? Seems a good idea to me.

**Comment by marinang** [comment]
No I don't have for the moment but I can try to make one, I was planning to work on hepstats today to make work, due to a new zfit version I have to change things (probably just the tests).
I am not an expert on designing logo, I did this one with Keynote actually 😅.
I never had the patience to tackle program like Gimp.

**Comment by marinang** [comment]
The logo has been updated in `hepstats`, so @mayou36 you can use that one instead.

**Comment by mayou36** [comment]
@eduardo-rodrigues okay thanks! Sure, I'll be.
Updated the logo @marinang merging

**Pull request merged**
