### PR TITLE
feat: add pycln as a recommendation

### PR DESCRIPTION
**Pull request by henryiii**
Linked: https://github.com/scikit-hep/cookie/pull/38

### CODE REVIEW

**Review by eduardo-rodrigues — APPROVED** [review]
No strong opinion on this recommendation. I actually think it is good that flake8 makes people realise that they are adding redundant imports.

**Comment by henryiii** [comment]
Pre-commit also does that; you can quickly see what's changed. Before development in git and pre-commit, auto-fixes might have been less useful, but now there's no need to not have an auto fix. It makes developing faster because you don't have to go back and manually remove the no-longer-needed lines. It's just an optional recommendation, though.

**Comment by eduardo-rodrigues** [comment]
That's a fair point.

**Comment by jonas-eschle** [comment]
Why not, indeed, it's nice

**Review by matthewfeickert — APPROVED** [review]
Thanks for this new recommendation @henryiii. As it is in addition to the Flake8 check this LGTM. :shipit:

**Pull request merged**
