### PR TITLE
feat: include pybind11 as an affiliated project

### PR DESCRIPTION
**Pull request by henryiii**
I think we should probably list this as well given we have quite a few projects depending on it, and we have maintainers on the team.

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
Hi @henryiii, TBH I think this is a bit over the top. You see, already cibuildwheel is not really an affiliated project/package in the same was as zfit obviously is. Now, if we keep adding such as pybind11 here, how about numpy and then scipy and then ...? Yes we build on various things, and some of us even contribute to other projects and packages, but that is not what an affiliated project is, really. I'm more than happy to see a discussion on the admins list to get the opinion from others. Mine is just posted. This is not to say that I do not appreciate the excellent packages/projects on which we depend and/or build.

**Comment by henryiii** [comment]
This is part of my original definition of "affiliated" project. I defined "affiliated" as we have at least one Scikit-HEP developer working on that project. @mayou36 works on ZFit. I work on GooFit, cibuildwheel, and pybind11. @chrisburr and I work on conda-forge/root-feedstock. Each of our "affiliated" projects has a Scikit-HEP developer on the maintainer team. It's a clear line on what can be "affiliated" and what can't; if we had added this to our official description of what affiliated means, then this would not be unclear now.

This means that if something comes up that affects Scikit-HEP, we have a say and a stake in the direction of those projects. We do not have a say in NumPy, SciPy, or Cython's direction. If Cython choses to make a change that breaks all of our packages, we can't stop that; but we do have a say in what pybind11 does. If someone uses Scikit-HEP, they can be assured that the affiliated packages play well with our packages - If they choose pybind11, they can extend awkward, boost-histogram, iminuit, etc. Cython users are on their own, we have no control over that and we are slowly removing our support for Cython extensions.

We used to have a package for building wheels (azure-wheel-helpers), but we replaced it with cibuildwheel. It was a clear need for Scikit-HEP, and we chose to support (and join) an external package instead of continuing to develop our own. The same thing is true for pybind11, except we didn't start by writing our own tool (as in Scikit-HEP, not the HEP community, which did with ROOT's C++ binding tooling, of course).

That's my opinion, anyway. If others disagree, happy to drop this.

**Comment by henryiii** [comment]
For example, faster memory-efficient accumulation support was added to pybind11 because we needed it in Scikit-HEP (boost-histogram).  Quite a bit of the new setuptools and CMake functionality updates started out in Scikit-HEP project (boost-histogram, awkward). The pybind/cmake_example updates were heavily inspired and influenced by iminuit and awkward.

**Comment by henryiii** [comment]
And Scikit-HEP got mentioned several times in the pybind11 SciPy talk. :)

**Comment by eduardo-rodrigues** [comment]
Seems we both forgot about this thread. I take your good points and thank you for spelling those out so clearly. Got it. I will have to check later how we define affiliated but right now I agree with the consistency scenario you describe. Merging this to avoid further delays (no other admin shouted so that's OK, right?).

**Pull request merged**
