### PR TITLE
add doc url in hepstats.yml

### PR DESCRIPTION
**Pull request by marinang**

### CODE REVIEW

**Comment by marinang** [comment]
@eduardo-rodrigues  absolutely, I will have a look on how it is done.

**Comment by marinang** [comment]
Hum as I don't find out how to do it can you tell me how the `root-numpy` doc was put under  scikit-hep.org/ ?

**Comment by eduardo-rodrigues** [comment]
@marinang, I will have to find that out as well, actually. It does not seem obvious. Hmm … Let's try and find out … I'm merging this anyway.

**Comment by eduardo-rodrigues** [comment]
Wait, I see that the pyhf team does put its doc under scikit-hep.org/pyhf, which is great. @matthewfeickert, @kratsg, could you let us know how that's done, so that we reproduce the flow for this package? Many thanks.

**Comment by kratsg** [comment]
Hi, nothing magical about it. Just use `gh-pages` and it'll deploy to the subfolder by default: 
Screenshot 2020-02-18 22 28 17

**Comment by eduardo-rodrigues** [comment]
Thanks. Well, that implicit simplicity is what I call magic ;-). I see that the specific gh-pages branch needs to be created ...

**Comment by marinang** [comment]
No a `gh-pages` is not needed anymore, it can just build using the  docs folder.

**Comment by eduardo-rodrigues** [comment]
OK OK.

**Comment by eduardo-rodrigues** [comment]
@marinang, I see in https://github.com/scikit-hep/hepstats/settings that the docs are/will now being/be published at scikit-hep.org/hepstats. So you updated things? Is that just a matter of redoing a release?

It is a good thing to enforce HTTPS. There's a check button for it.

**Comment by marinang** [comment]
Yeah the doc is online in https://scikit-hep.org/hepstats/, the rendering is not working though but I think I know why.

**Pull request merged**
