### PR TITLE
Actually use Python 2.7 in win-py27 job

### PR DESCRIPTION
**Pull request by webknjaz**

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
Thanks for spotting the typo. CC @henryiii.

**Comment by henryiii** [comment]
This is **not a typo**! `cibuildwheel` can build any version of Python from any version of Python, but it requires the host to have 3.6+ to run. So this is now broken. Notice the other jobs build all the other versions of Python but only have a single host 3.7 Python. This is not different because it only runs one job.

**Comment by webknjaz** [comment]
Oh, then it's better to add some code comment there...

**Comment by henryiii** [comment]
I did. It's more obvious on the one above it, where all Python versions get built, I see that it could be a a little surprising on this one. I _could_ leave off the number, I think GHA defaults to something more than 3.5, but I don't think they promise anything specific about the version you get by default, so I lock the version here. Maybe it would be cleaner/clearer though.

If a runner defaulted to 2.7 I'd throw a fit...

**Comment by henryiii** [comment]
It looks like setup-python's default is `3.x`, which is the most recent Python supported. Since cibuildwheel is already being tested on 3.9-dev, I think we should be pretty safe in using the default even when it becomes 3.9 in the fall. I'll make a PR.

**Comment by henryiii** [comment]
The unknown Python version behavior they describe is if you don't call setup python, not if you call it with the default. :)

**Pull request merged**
